### ISSUE TITLE
SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:3306 inside DevContainer

### ISSUE THREAD

**Issue by Nowocyn** [damms005/devdb-vscode#43]
### Extension Version

v1.0.12

### OS and Version

Windows 11 / WSL (Ubuntu 22.04 + Docker)

### VS Code Version

Version: 1.85.2 (user setup) Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681 Datum: 2024-01-18T06:40:10.514Z Electron: 25.9.7 ElectronBuildId: 26354273 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 Betriebssystem: Windows_NT x64 10.0.22621

### Database name and Version

mysql/mysql-server:latest

### Steps to reproduce

1. Create laravel application with sail and --devcontainer option to get started with vscode devcontainer and laravel.
2. Open project within the devcontainer.
3. Try to open view DevDB view.  
The Error appears and there is only the option to open a SQLite Database, but there is a mysql connection given in the .env file.

### Expected behavior

Give me multiple options for databases to view. 

### Screenshots

Error: 
![image](https://github.com/damms005/devdb-vscode/assets/140813072/9af15d55-047e-47f8-8e4c-aaebd08ff394)
![image](https://github.com/damms005/devdb-vscode/assets/140813072/90b8c7a3-cfa5-437e-be54-ec7894e96019)
`.env`:
![image](https://github.com/damms005/devdb-vscode/assets/140813072/76f34225-49ae-4f17-ac7b-0241c829d4f6)
`docker-compose.yml`:
![image](https://github.com/damms005/devdb-vscode/assets/140813072/c95375d2-f488-4621-8207-2ca45f96bed3)

### Additional context

DevDB is not showing from where the requested ip 127.0.0.1 (default loopback ip) is coming from. It seem like it is not using the .env or detecting the laravel instance in the devcontainer.

**Comment by damms005** [comment]
Hello @Nowocyn , sorry for bot-closing this. It was due to sloppy regex. Now fixed.

Per your issue, I think it is related to DevDb not currently having support for mariadb and/or some Windows WSL issue. I currently use Linux and hence I do not have a windows system to repro this at the moment. So, I will leave this closed for now.

I am however open to reviewing a PR that addresses this.

Thank you.

**Comment by RecklessBoon** [comment]
I am also coming across this same issue. I'm attaching my VS Code workspace to a running docker instance and it seems to only be trying to connect to the loop back address rather than using the settings in my .env. I'm running Windows 11 with WSL2 backed Docker Engine and using Laravel 11 with sail.

**Comment by damms005** [comment]
@RecklessBoon Correct me if I am wrong but either sail/devcontainer/wsl or whatever you are using in your local development is still localhost. The only difference is that the port should be different, right?

Or perhaps the fix here is to use `localhost` instead of the [currently used loopback address](https://github.com/damms005/devdb-vscode/blob/main/src/services/laravel/env-file-parser.ts#L38)?

**Comment by RecklessBoon** [comment]
Actually, it's the opposite with a different host name but same port. The db is running in a different container, and the hostname is the container name. The default for sail appears to be "mysql" as the hostname.

**Comment by RecklessBoon** [comment]
Really, the connection info should match what is in .env which has the correct hostname and port.

**Comment by damms005** [comment]
Seems you don't get my point. I'll give more details:

- Configuration specified in `.env` in a Sail application is essential for `docker-compose.yml`. It is for comunication across containers. 
- DevDb does not run in container, so it needs to access the database from *outside* the container
- Hence, why DevDb actually really needs the *port* the database is running in the *host* (which is most likely always _localhost_)

Makes sense?

**Comment by RecklessBoon** [comment]
If I was running my VS Code from my desktop, sure that'd make sense. However, I am running VS Code attached to the app container (within the container). Since it is in the container, Vs Code runs in the containers network, not the host machine's. I do this so I don't have to type "sail" before every command and my extensions can utilize the build tools installed in the container. I have a .devdbrc with the same connection name and it works with "mysql". If this scenario isn't going to be supported, that's fine, but it should probably be noted in the "no-config" section of the readme.

**Comment by RecklessBoon** [comment]
Apologies, I wasn't clear on my setup!

**Comment by damms005** [comment]
Oh that kinds makes sense now. Yeah so your db server is definitely not on localhost that way.

I'm not sure how extensions work in "VS Code attached to the app container", so not sure if I will be supporting this feature yet. Good thing `devdbrc` covers this already.

**Comment by Nowocyn** [comment]
@damms005 thanks for your answers. 

Would the following scenario be possible without many changes?
Use the `env` variable `DEVDB_HOST_FROM_ENV=true` and read the given host from `DB_HOST` instead of using the default one and the default value of this configuration will be `false` so that only the user of a dev container will set it and also will set it to true. 

Would be the perfect situation for these lines without changing a lot:
https://github.com/damms005/devdb-vscode/blob/86f419fbf94fa1724e0049cb79f53c6e5da85a13/src/services/laravel/env-file-parser.ts#L42

Your answers were very helpful thanks a lot. 
Or should I create a fork with a PR with the wanted changes?

**Comment by damms005** [comment]
Yeah your suggestion is awesome and I love it! Thanks, @Nowocyn 

I'll appreciate if you can open a PR that addresses this and I'll be glad to review and merge.

PS: I'd suggest you consider a `DEVDB_HOSTNAME=<hostname.to.connect>` variable in `env` file instead of `DEVDB_HOST_FROM_ENV=true`. Then if this value exists and is filled DevDb uses that. It will solve this issue and other cases that the host differes for whatever reason or just want to debug other databases. I think this approach will just open up some other use-cases.

Thoughts?

**Comment by damms005** [comment]
Just documenting my thoughts here...

https://masteringlaravel.io/daily/2024-06-11-what-is-the-difference-between-localhost-and-127001
