### ISSUE TITLE
does not display connections

### ISSUE THREAD

**Issue by Under0Cover** [damms005/devdb-vscode#51]
### Extension Version

v1.3.2

### OS and Version

Ubuntu 22.04.3 LTS

### VS Code Version

v1.86.2

### Database name and Version

mysql  Ver 8.0.36 for Linux on x86_64 (MySQL Community Server - GPL)

### Steps to reproduce

Steps I followed:
- I installed the extension through VScode
- I configured the .devdbrc file according to the information provided on the plugin's home page
- The first time, the extension was able to find both the .devdbrc file, and it was also able to automatically find Laravel
- The use is being made by a notebook. What I did a few times, close the notebook without shutting down and closing vscode
- When I used the extension, it was no longer able to identify the .devdbrc file and neither was Laravel

I had no problems using any Laravel functionality related to the database (factories, seeders, migrations)

### Expected behavior

As soon as I installed and configured it, I was able to use the extension correctly. I hoped to continue using

### Screenshots

![image](https://github.com/damms005/devdb-vscode/assets/60072961/8fef6266-1895-4216-9f41-45ba201c790c)

**Comment by betsaleel777** [comment]
i have the same issue

**Comment by betsaleel777** [comment]
v1.7.14 i'm using vscodium a fork of vscode on archlinux garudalinux distribution.
Nice job, you are a genius, i am very excited to use this extension. i'm come from côte d'ivoire.  please help

**Comment by damms005** [comment]
@betsaleel777 I cannot guarantee that DevDb will work with forks of VS Code because I only use VS Code.

However, if you can open a PR that addresses your issue, I am open to reviewing it.

**Comment by Jas-n** [comment]
I have the same issue, but I've figured out it's down to my `DB_CONNECTION=mariadb` on Laravel. Changing it to `DB_CONNECTION=mysql` and refreshing, then changing it back still works.

1. Could that be the issue here?
2. Can we have a patch for mariadb?
Thank you.

**Comment by it-moisesmoreno** [comment]
### Extension Version
v1.9.1

### OS and Version
Kubuntu 24.04

### VS Code Version
v1.89.1

### Database name and Version
Server version: 10.11.7-MariaDB-2ubuntu2 Ubuntu 24.04

### Type of installation,  Hosted hypervisor and Version
Virtualization, VirtualBox Version 7.0.10 r158379 (Qt5.15.2)


### Steps to reproduce

Steps I followed:

- I installed the extension through VScode
- I configured the .devdbrc file according to the information provided on the plugin's home page
- The extension wasn't able to find the .devdbrc file
- I closed and reopened VScode
- The extension wasn't able to find the .devdbrc file
- I tried the refresh button
- The extension wasn't able to find the .devdbrc file

I'm working with a CodeIgniter project

### Expected behavior

As soon as I installed and configured it, I wasn't able to use the extension correctly. I hope to continue using

### Screenshots
![Screenshot_20240522_105805_devdb](https://github.com/damms005/devdb-vscode/assets/130410927/215f6ebe-c3a1-4b5d-9f82-74cdc46d1bfa)

**Comment by mattiadelfranco** [comment]
Hi, I have the same problem, can't see any database also by configurating a custom .devdbrc

**Comment by damms005** [comment]
@mattiadelfranco You may have to open a separate issue, so you can provide relevant context.
