### ISSUE TITLE
Table Tab Duplicates

### ISSUE THREAD

**Issue by NomadicDaddy** [damms005/devdb-vscode#72]
### Extension Version

v1.14.1

### OS and Version

Windows 11

### VS Code Version

v1.93.1

### Database name and Version

SQLite v3.46.0

### Steps to reproduce

From the table list once a database is selected, clicking on a table name more than once will open a new tab each time.

### Expected behavior

Once a table is opened in a tab, clicking on the table name from the list should focus the already opened tab, not open a new tab.

### Screenshots

![image](https://github.com/user-attachments/assets/0008bb7f-4716-4620-897a-018458c67871)

**Comment by damms005** [comment]
This is a feature, not a bug, as it is the expected behavior.

To focus an existing tab, simply click on the tab.

To load a new table into an existing, currently active tab, you should `Ctrl + Click` it, [as documented](https://github.com/damms005/devdb-vscode?tab=readme-ov-file#other-features)

Hope you find DevDb helpful!
